a = input ('Digite algo ')
print ('O tipo digitado é: {}{}{}  '.format('\33[7;4m',a,'\33[m'))
print (' É um espaco em branco ?' , a.isspace())
print  (' É um número ? ' , a.isnumeric() )
print (' É alfabetica ? ', a.isalpha())
print ('É alfanumérica?  ', a.isalnum() )
print ('Ésta em maiusculas ?' , a.isupper())
print ('Está em minusculas?' , a.islower())
print (' Esta capitalizada ?' , a.istitle())